sliderd: sliderd.c spi_util.c spi_util.h
	gcc sliderd.c spi_util.c -o ./bin/sliderd

spi_command_line: spi_command_line.c spi_util.c spi_util.h
	gcc spi_command_line.c spi_util.c -o ./bin/spi_command_line